project:
  type: website
  output-dir: docs

website:
  title: "FortificaciÃ³n de alimentos a gran escala"
  description: "sitio web para asistencia tÃ©cica de fortificaciÃ³n de alimentos"
  favicon: favicon.png
  reader-mode: true
  search:
    location: navbar
    type: overlay
  navbar:
    pinned: true
    logo: logo.png
    left:
      - href: index.qmd
        text: "ğŸ  Home"
      - href: about.qmd 
        text: "ğŸ“„ About" 
  sidebar:
    contents: auto

format:
  html:
    theme:
      - lumen
      - brand
    css: styles.css
    toc: true

editor: visual

